"""Train and evaluate Component B (supervised triage / confidence score).

    python -m ml.training.train_triage
    python -m ml.training.train_triage --save

Evaluated on **corpus rows only**, for the reason in `server/engine/ml_triage.py`: all
positives are corpus rows and the local rows are 100% benign, so a supervised learner would
otherwise use `sysmon_available` as a free label proxy.

Calibration is reported next to discrimination throughout. A model that ranks well but is
badly calibrated cannot be shown to an analyst as a confidence.
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone

import numpy as np

from ml.datasets import assemble as A
from ml.datasets.otrf_etl import DEFAULT_TRAIN_DB
from ml.evaluation import harness as H
from server.engine import ml_features as mlf, ml_triage

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
MODELS_DIR = os.path.join(_PROJECT_ROOT, "models")
REPORTS_DIR = os.path.join(_PROJECT_ROOT, "reports_ml")


def evaluate(dataset: A.Dataset, train_db: str, n_splits: int = 5) -> dict:
    eval_mask = H.corpus_eval_mask(dataset)
    corpus = dataset.subset(eval_mask)      # train AND evaluate on the corpus population
    print(f"corpus-only population: {len(corpus)} rows, {corpus.n_positive} positive, "
          f"{len(set(corpus.groups))} groups\n")

    results = [
        H.chance_baseline(corpus),
        H.sigma_baseline(corpus, train_db),
        H.best_single_feature_baseline(corpus, tier=mlf.TIER_T1, n_splits=n_splits),
    ]

    tier_results = {}
    # T3 is evaluated but never saved: it answers "what would enabling PowerShell module
    # logging buy?", which is a deployment recommendation, and a recommendation needs a
    # reproducible number rather than a remembered one.
    for tier in (mlf.TIER_T1, mlf.TIER_T2, mlf.TIER_T3):
        res = H.grouped_cv(
            corpus,
            fit_score=ml_triage.fit_score_factory(),
            tier=tier,
            n_splits=n_splits,
            name=f"triage_gbdt_{tier}",
            benign_only_fit=False,          # supervised: needs both classes
        )
        tier_results[tier] = res
        results.append(res)

    # Uncalibrated comparison: shows what calibration costs in ranking and buys in reliability.
    uncal = H.grouped_cv(corpus, ml_triage.fit_score_factory(calibrate=False),
                         tier=mlf.TIER_T1, n_splits=n_splits,
                         name="triage_gbdt_t1_uncalibrated", benign_only_fit=False)
    results.append(uncal)

    # ---- LEAK AUDIT.
    # Labels were generated by seed signatures (-enc <base64>, -w hidden, IEX, ...) and several
    # features restate those same patterns. Without this the headline could simply be the
    # classifier rediscovering the labelling rule. The gap between the two runs is the honest
    # size of that circularity.
    no_echo_features = mlf.features_excluding("seed_echo", tier=mlf.TIER_T1)
    no_echo = H.grouped_cv(corpus, ml_triage.fit_score_factory(), tier=mlf.TIER_T1,
                           n_splits=n_splits, name="triage_gbdt_t1_no_seed_echo",
                           benign_only_fit=False, feature_subset=no_echo_features)
    results.append(no_echo)

    # Harsher still: drop the entire command-line family, which the seeds are written over.
    no_cmdline_features = mlf.features_excluding("cmdline", "seed_echo", tier=mlf.TIER_T1)
    no_cmdline = H.grouped_cv(corpus, ml_triage.fit_score_factory(), tier=mlf.TIER_T1,
                              n_splits=n_splits, name="triage_gbdt_t1_no_cmdline_at_all",
                              benign_only_fit=False, feature_subset=no_cmdline_features)
    results.append(no_cmdline)

    H.print_report(results, title="Component B - supervised triage (corpus rows only)")

    print("\n--- calibration (the reason this component exists) ---")
    calibration = {}
    for name, res in list(tier_results.items()) + [("t1_uncalibrated", uncal)]:
        key = name if isinstance(name, str) else str(name)
        metrics = H.calibration_metrics(corpus.y, res.scores)
        calibration[key] = metrics
        print(f"\n  [{key}] brier={metrics['brier_score']} "
              f"(base-rate predictor {metrics['brier_of_base_rate_predictor']}) "
              f"skill={metrics['brier_skill_score']} ece={metrics['expected_calibration_error']}")
        print(f"        mean predicted={metrics['mean_predicted']} vs base rate {metrics['base_rate']}")
        for b in metrics["bins"]:
            print(f"          {b['bin']:>12s} n={b['n']:>5d} predicted={b['mean_predicted']:.3f} "
                  f"observed={b['observed_frequency']:.3f} gap={b['gap']:+.3f}")

    # Component A vs B on identical rows and folds.
    from server.engine import ml_anomaly
    anomaly = H.grouped_cv(corpus, ml_anomaly.fit_score_factory(), tier=mlf.TIER_T1,
                           n_splits=n_splits, name="anomaly_iforest_t1(for comparison)",
                           benign_only_fit=True)
    results.append(anomaly)
    print("\n--- Component A (unsupervised) vs Component B (supervised), same folds ---")
    print(H.comparison_table([anomaly, tier_results[mlf.TIER_T1]])[
        ["model", "pr_auc", "roc_auc", "recall_at_fpr_0.01", "precision_at_25", "pr_auc_ci"]
    ].to_string(index=False))

    complementarity = H.sigma_complementarity(
        corpus, results[1].scores, tier_results[mlf.TIER_T1].scores)
    print("\n--- does Component B find what the Sigma rules miss? ---")
    print(json.dumps(complementarity, indent=2))

    print("\n--- per-fold stability ---")
    for tier, res in tier_results.items():
        pr = [f["pr_auc"] for f in res.per_fold if f.get("pr_auc") is not None]
        if pr:
            print(f"  {tier}: {[round(p, 3) for p in pr]}  "
                  f"mean={np.mean(pr):.3f} sd={np.std(pr):.3f}")

    full_pr = tier_results[mlf.TIER_T1].metrics.get("pr_auc")
    leak_audit = {
        "note": "labels come from seed signatures; these features restate them. The drop is "
                "the honest size of the circularity.",
        "seed_echo_features": list(mlf.SEED_ECHO_FEATURES),
        "pr_auc_all_features": full_pr,
        "pr_auc_without_seed_echo": no_echo.metrics.get("pr_auc"),
        "pr_auc_without_any_cmdline": no_cmdline.metrics.get("pr_auc"),
        "drop_from_removing_seed_echo": (
            None if None in (full_pr, no_echo.metrics.get("pr_auc"))
            else round(full_pr - no_echo.metrics["pr_auc"], 4)),
        "recall_at_fpr_0.01": {
            "all_features": tier_results[mlf.TIER_T1].metrics.get("recall_at_fpr_0.01"),
            "without_seed_echo": no_echo.metrics.get("recall_at_fpr_0.01"),
            "without_any_cmdline": no_cmdline.metrics.get("recall_at_fpr_0.01"),
        },
    }
    print("\n--- LEAK AUDIT: how much of the result is the labelling rule? ---")
    print(json.dumps(leak_audit, indent=2))

    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "feature_spec_sha256": mlf.feature_spec_sha256(),
        "leak_audit": leak_audit,
        "population": {"rows": len(corpus), "positives": corpus.n_positive,
                       "groups": len(set(corpus.groups)),
                       "note": "corpus rows only - local rows excluded to remove the "
                               "source/label confound"},
        "n_splits": n_splits,
        "results": {r.name: {"metrics": r.metrics, "ci": r.ci, "per_fold": r.per_fold,
                             "extra": r.extra} for r in results},
        "calibration": calibration,
        "sigma_complementarity": complementarity,
    }


def fit_final(dataset: A.Dataset, tier: str):
    corpus = dataset.subset(H.corpus_eval_mask(dataset))
    X, stats = A.materialise(corpus, train_mask=None, tier=tier)
    model = ml_triage.TriageModel().fit(X, corpus.y)
    model.fit_explainer(X)
    return model, stats


def save(model, stats, tier: str, metrics: dict, calibration: dict) -> str:
    import joblib
    os.makedirs(MODELS_DIR, exist_ok=True)
    path = os.path.join(MODELS_DIR, f"triage_{tier}.joblib")
    joblib.dump({
        "kind": "triage",
        "tier": tier,
        "payload": model.to_payload(),
        "feature_stats": stats.to_dict(),
        "feature_spec_sha256": mlf.feature_spec_sha256(),
        "metrics": metrics,
        "calibration": calibration,
        "trained_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }, path)
    return path


def main() -> int:
    ap = argparse.ArgumentParser(description="Train/evaluate Component B")
    ap.add_argument("--train-db", default=DEFAULT_TRAIN_DB)
    ap.add_argument("--live-db", default=A.DEFAULT_LIVE_DB)
    ap.add_argument("--splits", type=int, default=5)
    ap.add_argument("--save", action="store_true")
    ap.add_argument("--report", default=os.path.join(REPORTS_DIR, "triage_eval.json"))
    args = ap.parse_args()

    dataset = A.load(args.train_db, args.live_db, include_local=True)
    if len(dataset) == 0:
        print("dataset empty - run the Phase 1 ETL first")
        return 1

    report = evaluate(dataset, args.train_db, n_splits=args.splits)
    os.makedirs(os.path.dirname(args.report), exist_ok=True)
    with open(args.report, "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, default=str)
    print(f"\nreport written: {args.report}")

    if args.save:
        for tier in (mlf.TIER_T1, mlf.TIER_T2):
            model, stats = fit_final(dataset, tier)
            print(f"saved: {save(model, stats, tier, report['results'][f'triage_gbdt_{tier}']['metrics'], report['calibration'].get(tier, {}))}")
    return 0


if __name__ == "__main__":       # pragma: no cover - operator entry point
    raise SystemExit(main())
